version: "3"

services:
  mailmanagerbackend:
    image: mailmanagerbackend
    stdin_open: true
    build: ../backend/api
    volumes:
      - ../backend/api:/user/src/app
    # depends_on:
    #   - database
    ports:
      - "2000:2000"
    restart: always
    networks:
      - front
      - back

  # database:
  #   image: database
  #   build: ../backend/database
  #   volumes:
  #     - ../backend/database/data:/data/db
  #   restart: always
  #   networks:
  #     - back

  # Frontend / App / Web
  mailmanagerweb:
    image: mailmanagerweb
    build: ../frontend/app/web
    restart: always
    stdin_open: true
    ports:
      - "3000:3000"
    tty: true
    depends_on:
      - mailmanagerbackend
    volumes:
      - ../frontend/app/web/src:/user/src/app/src
    networks:
      - front

networks:
  front:
    driver: bridge
  back:
    driver: bridge
  docker-network:
    driver: bridge
