export const MailTemplatesActionTypes = {
  UPDATE_MAIL_TEMPLATES: "UPDATE_MAIL_TEMPLATES",
  FETCH_MAIL_TEMPLATES_START: "FETCH_MAIL_TEMPLATES_START",
  FETCH_MAIL_TEMPLATES_SUCCESS: "FETCH_MAIL_TEMPLATES_SUCCESS",
  FETCH_MAIL_TEMPLATES_FAILURE: "FETCH_MAIL_TEMPLATES_FAILURE",
};

export default MailTemplatesActionTypes;
